### PR TITLE
Makefile

### PR DESCRIPTION
**Pull request by mjtrangoni**
Hi @christoe, @davidkarlsen,

I hope you find my changes useful, and I know you will have to fix the `Dockerfile`, but here is a `Makefile` implementation with some nice extras,

1. Implement a Makefile with many targets.
1. Use [dep](https://github.com/golang/dep) instead of `govendor`. 
    > The  goal with dep is to be absorbed into the go toolchain. That's the path we're on, but it's up to the Go community - you! - to help us see it through.
1. Use `kingpin` instead of `flag`.
1. Fix some [gometalinter](https://github.com/alecthomas/gometalinter) issues.
1. Use [promu](https://github.com/prometheus/promu).

You can make some changes or cherry-pick these changes as you want.

Thanks!

### CODE REVIEW

**Comment by davidkarlsen** [comment]
That looks nice - I'm not a committer myself - but one thing to be aware of is that docker hub automated/trusted builds are based on Dockerfiles only and no Makefiles.

**Comment by mjtrangoni** [comment]
@davidkarlsen Ok, It would be nice pointing [this](https://hub.docker.com/r/davidkarlsen/logstash_exporter/) at the README file.

By the way, I think this could be automatically deployed using `make` and then `docker build..` with CircleCI. Thanks!

**Comment by christoe** [comment]
Thanks @mjtrangoni! I will be looking into this shortly. Changes look good from a quick glance - would you mind squashing the commits?

**Comment by mjtrangoni** [comment]
Hi @christoe, does it look better now?

**Comment by christoe** [comment]
@mjtrangoni: Thank you very much!

**Pull request merged**
