### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by davidkarlsen**
Here is a Dockerfile which you could use for automated builds: https://docs.docker.com/docker-hub/builds/

### CODE REVIEW

**Comment by davidkarlsen** [comment]
WDYT?

**Comment by carlpett** [comment]
Hey,
Sorry about the lack of response on this! Seems like none of the maintainers have notifications set on the repo. I'll make sure this is looked at tomorrow!

**Comment by christoe** [comment]
@davidkarlsen: Thanks for your contribution, and yet again - sorry about the lack of response! I've now merged your PR with a small modification.

**Comment by davidkarlsen** [comment]
Great - will you also setup an automated build on docker hub for this repo?

**Comment by christoe** [comment]
@davidkarlsen: Yes, here: https://hub.docker.com/r/bonniernews/logstash_exporter/

**Comment by olvesh** [comment]
Just a little notice from the sideline. If you create an automated build in docker hub it will be transparent and verified. The way it is done now I don't know what will happen if I run the image on the link since I have no easy way of verifying the image.

**Comment by davidkarlsen** [comment]
+1 to that - compare your image with https://hub.docker.com/r/davidkarlsen/logstash_exporter/ which has backlings to the original source. Also some stable tags/branches would be preferrable

**Comment by davidkarlsen** [comment]
@christoe Any update on the "trusted build" issue?

**Comment by carlpett** [comment]
@christoe is on vacation, but I believe he was working on this. As far as I recall, there was an issue with setting up the automated builds when the target was an organization account, rather than a personal one. 
I'll see if I can figure it out, otherwise I think he's back next week. Sorry about the slowness here.

**Comment by carlpett** [comment]
Apparently it is not possible to add automated builds to an existing repo on Docker hub(?!), but removing and re-creating it seems to have worked. Build should be finished in a minute or two!
@davidkarlsen, does this look like what you wanted?

**Comment by davidkarlsen** [comment]
Yes - this is what we want - great work!

**Pull request closed without merging**
