### PR TITLE
Add 4 missing duration and queue size metrics

### LINKED ISSUE #17: Add queue_size_in_bytes metrics
In Queue `capacity` stats there is also `queue_size_in_bytes` which ATM is not collected.

This metric is particullary useful to calculate queue usage percentage: `queue_size_in_bytes/max_queue_size_in_bytes`

### PR DESCRIPTION
**Pull request by rifelpet**
This adds the following metrics:

```
logstash_node_queue_size_bytes{pipeline="main"} 1.4235844e+07
logstash_node_pipeline_queue_push_duration_seconds_total{pipeline="main"} 382
logstash_node_plugin_queue_push_duration_seconds_total{pipeline="main",plugin="beats",plugin_id="beats",plugin_type="input"} 0
logstash_node_plugin_duration_seconds_total{pipeline="main",plugin="elasticsearch",plugin_id="es",plugin_type="output"} 67
```

This resolves #17

### CODE REVIEW

**Comment by tivvit** [comment]
I think this should be merged, the metrics are missing

**Comment by tivvit** [comment]
I tested the code and it works

**Comment by danielmotaleite** [comment]
This repo is dead, use the below fork  #35

**Comment by rifelpet** [comment]
closing because the fork mentioned above includes this PR and we'll be switching to that.

**Pull request closed without merging**
