### PR TITLE
Multi-stage build for minimal image

### PR DESCRIPTION
**Pull request by davidkarlsen**
also upgrade to golang:1.8
still need glibc

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@christoe @carlpett

**Comment by davidkarlsen** [comment]
Bugger - I just noticed docker hub does not offer multistage builds yet: https://github.com/docker/hub-feedback/issues/1039

**Comment by christoe** [comment]
Thanks @davidkarlsen, I will merge this as soon as we get a green light on multistage builds in Docker Hub.

**Comment by davidkarlsen** [comment]
@christoe I think you are good to go now: https://github.com/docker/hub-feedback/issues/1039#issuecomment-323761501

**Comment by christoe** [comment]
@davidkarlsen: Seems like it was rolled back, but any day now.. https://github.com/docker/hub-feedback/issues/1039#issuecomment-323857796

**Pull request merged**
